FROM openshift/origin-release:golang-1.10
COPY . /go/src/github.com/kubernetes-csi/driver-registrar/
RUN cd /go/src/github.com/kubernetes-csi/driver-registrar/ && \
    go build ./cmd/driver-registrar

FROM centos:7

COPY --from=0 /go/src/github.com/kubernetes-csi/driver-registrar/driver-registrar /usr/bin/

RUN useradd csi-attacher
USER csi-attacher

CMD ["/usr/bin/driver-registrar"]
